services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./StoryWeaver_V2_Frontend/dist:/usr/share/nginx/html
    networks:
      - storyweaver-network
  backend:
    build:
      context: ./StoryWeaver_V2_Backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    hostname: backend
    restart: always
    volumes:
      - ./StoryWeaver_V2_Backend:/app:delegated
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - APP_URL=http://api.storyweaver.localhost
      - FRONTEND_URL=http://frontend.storyweaver.localhost
      - SESSION_DOMAIN=.storyweaver.localhost
      - DB_HOST=db
      - DB_DATABASE=storyweaver_dev
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
      - MAIL_HOST=mailcatcher
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
    networks:
      - storyweaver-network
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    hostname: mailcatcher
    ports:
      - '1080:1080' # Web UI
      - '1025:1025' # SMTP server
    networks:
      - storyweaver-network
  frontend:
    platform: linux/amd64
    build:
      context: ./StoryWeaver_V2_Frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "4200:4200"
    networks:
      - storyweaver-network
    volumes:
      - ./StoryWeaver_V2_Frontend:/app:delegated
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
      - ./redis.conf:/etc/redis/redis.conf
    depends_on:
      - db
    networks:
      - storyweaver-network
  db:
    container_name: db
    hostname: db
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=storyweaver_dev
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - storyweaver-network

volumes:
  cache:
    driver: local
  db-volume:
    driver: local
networks:
  storyweaver-network:
    external: false