version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./StoryWeaver_V2_Frontend/dist:/usr/share/nginx/html
    networks:
      - storyweaver-network

  backend:
    build:
      context: ./StoryWeaver_V2_Backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    hostname: backend
    restart: always
    volumes:
      - ./StoryWeaver_V2_Backend:/app:delegated
      - /app/vendor
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - storyweaver-network

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    hostname: mailcatcher
    restart: always
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP server
    networks:
      - storyweaver-network

  frontend:
    platform: linux/amd64
    build:
      context: ./StoryWeaver_V2_Frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "4200:4200"
    networks:
      - storyweaver-network
    volumes:
      - ./StoryWeaver_V2_Frontend:/app:delegated
      - /app/node_modules
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - storyweaver-network

  db:
    image: mysql:latest
    container_name: db
    hostname: db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=storyweaver_dev
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - storyweaver-network

volumes:
  cache:
    driver: local
  db-volume:
    driver: local

networks:
  storyweaver-network:
    external: false