services:
  backend:
    build:
      context: ./StoryWeaver_Backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    hostname: backend
    restart: always
    volumes:
      - ./StoryWeaver_Backend:/app:delegated
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "3000:3000"
      - "7001:22"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=storyweaver_dev
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password
    networks:
      - storyweaver-network
  frontend:
    build:
      context: ./StoryWeaver_Frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    hostname: frontend
    restart: always
    ports:
      - "4200:4200"
    networks:
      - storyweaver-network
    volumes:
      - ./StoryWeaver_Frontend:/app:delegated
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - backend
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
      - ./redis.conf:/etc/redis/redis.conf
    depends_on:
      - db
    networks:
      - storyweaver-network
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=storyweaver_dev
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - storyweaver-network

volumes:
  cache:
    driver: local
  db-volume:
    driver: local
networks:
  storyweaver-network:
    external: false